sudo: false
language: node_js
node_js:
  - "8"
cache: npm

install:
  - npm i npminstall && npminstall

stages:
  - build
  - deploy

jobs:
  include:
    - stage: build
      script:
        npm run lint
        npm run build
    - stage: deploy
      script:
        - echo "NPM Deploying Started ..."

      deploy:
        provider: npm
        email: "627230819@qq.com"
        api_key: $API_KEY
        on:
          branch: production

