sudo: false
language: node_js
node_js:
  - "8"
cache: npm

install:
  - npm i npminstall && npminstall

stages:
  - build
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      script:
        npm run lint
        npm run build

      deploy:
        on:
          branch = production
        provider: npm
        email: "627230819@qq.com"
        api_key: $API_KEY


