sudo: false
language: node_js
node_js:
  - "8"
install:
  - npm i npminstall && npminstall

stages:
  - build
  - name: publish
    if: branch = master

jobs:
  include:
    - stage: build
    script:
      npm run lint
      npm run build

    - stage: publish
    script:
      npm publish

